language: java
dist: trusty
jdk:
  - oraclejdk8
services:
  - docker
before_install:
  openssl aes-256-cbc -K $encrypted_1f529b35453a_key -iv $encrypted_1f529b35453a_iv -in deploy/travis/settings-security.xml.enc -out deploy/travis/settings-security.xml -d
script:
  - mvn -U --settings deploy/travis/settings.xml -Dsettings.security=deploy/travis/security-settings.xml -Dmaven.test.skip=true deploy clean package
