server:
  port: 5001
  servlet:
    context-path: /stock

spring:
  datasource:
    url: #
    username: #
    password: #
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZZ
    time-zone: GMT+8

stock:
  batch-inser-size: 10
  proxy:
    ip: 127.0.0.1:8080
    use-proxy: false
    exclude-url: 123

tushare:
  url: http://api.tushare.pro
  token: #

mybatis:
  mapper-locations: 'classpath:/mapper/**/*.xml'

#logging:
#  level:
#    root: DEBUG
#    org.dcais.stock: DEBUG
#    org:
#      springframework:
#        web: DEBUG
#    com.ibatis: WARN
#    java.sql: DEBUG
#    java.sql.ResultSet: DEBUG


